name: Get iOS IPA folder
on:
  workflow_dispatch:
    inputs:
      WORKSPACE_PATH:
        description: '[path].workspace (dont add workspace)'
        required: true
        default: 'Runner'

  push:
    branches:
      - build

jobs:
  # We are disabling ios because it consumes too many minutes in github action (regular min * 10)
  release-ios:
    name: IOS get IPA file
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: source/yarn.lock
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'

      - name: YARN Cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: pwd && cd source && yarn install
        
      - name: Install Ruby & Fastlane
        run: pwd && cd source && cd ios && bundle install

      - uses: ruby/setup-ruby@v1.82.0
        with:
          ruby-version: '2.7'
          bundler-cache: true
          working-directory: './source/ios'
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: ./source/ios/Podfile.lock
      - name: Pods Cache
        uses: actions/cache@v2
        with:
          path: ./source/ios/Pods
          key: ${{ runner.os }}-pods-v2-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-v2-

      - name: Install pods
        run: pwd && cd source && cd ios && pod install

      - name: Run iOS app
        run: pwd && cd source && npm run ios

      - name: Execute Fastlane command
      run: pwd && cd source && cd ios && bundle exec fastlane build_ios_app_and_get_ipa bundle_id:"${{ github.event.inputs.BUNDLE_ID }}" name:"${{ github.event.inputs.APP_NAME }}" sku:"${{ github.event.inputs.APP_SKU }}"
      env:
        #FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "nets-yxrj-qpzp-evbi"
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}

      # - name: Build iOS app with xcodebuild
      #   run: |
      #     cd source/ios
      #     xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/Runner.xcarchive

      # - name: Export .ipa file
      #   run: cd ios && xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build