name: GET Request Action With Authorization

on:
  workflow_dispatch:
    inputs:
      appId:
        description: 'App ID'
        required: true
        default: '2449'

jobs:
  make-get-request:
    runs-on: ubuntu-latest

    steps:
    - name: GET Request with Authorization
      env:
        APP_ID: ${{ github.event.inputs.appId || '2449' }} # Use input or default to '2449'
      run: |
        curl -X 'GET' \
        "https://stg-usersurveysite-beehivestag.kinsta.cloud/wp-json/wp/v2/apps/${APP_ID}" \
        -H 'accept: application/json' \
        -H 'authorization: Basic Y2hyaXNAY2hyaXN0b3BoZXJrZW5kcmljay5pbzpDYW1kZW5vdHQxMjM0NSE='
